---

   - name: Install prerequisites
     package:
      name: "{{ item }}"
      update_cache: yes
     with_items: "{{ consul_install_prerequisites }}"
     become: yes
   - name: Download binary
     get_url:
       url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
       dest: /tmp/consul_{{ consul_version }}_linux_amd64.zip
       owner: "{{ consul_user }}"
       group: "{{ consul_group }}"
       mode: 0755
       checksum: "{{consul_checksum}}"
     register: consul_download
   - name: "Unzip consul archive"
     unarchive:
        src: /tmp/consul_{{ consul_version }}_linux_amd64.zip
        dest: /usr/bin
        copy: no
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0755
